refactor: breaking api changes
ethersphere/bee-js pull request #105
Opened 2021-02-04 19:32 UTC by agazso

2021-02-04 21:03 UTC, vojtechsimetka commented
One suggestion. If this is breaking change on our interface, you may want to add `!` after the scope (in this case `refactor!: ...` ). This way it will be properly caught by the `please-release` system and it will be listed in the breaking changes.

2021-02-08 14:24 UTC, nugaon requested changes

2021-02-08 14:24 UTC, nugaon commented on src/chunk/upload.ts
> +export function uploadSingleOwnerChunk(
It is purely only a SOC function, that could be moved to `src/chunk/soc.ts`

2021-02-08 14:46 UTC, agazso commented on src/chunk/soc.ts
> +    throw e
Good catch, I will remove the `try ... catch`

2021-02-08 17:51 UTC, vojtechsimetka approved these changes

2021-02-08 17:51 UTC, vojtechsimetka commented on .github/workflows/ci.yaml
> +          # sed -i 's/IMAGE_TAG="latest"/IMAGE_TAG="0.4.2"/' beeinfra.sh
Just so we don't forget about this :)
```suggestion
          sed -i 's/IMAGE_TAG="latest"/IMAGE_TAG="0.5.0"/' beeinfra.sh
```

2021-02-09 08:40 UTC, nugaon approved these changes

2021-02-09 08:40 UTC, nugaon commented on src/modules/debug/settlements.ts
> +  received: number | null
I would write `received?: number` instead of that

2021-02-09 08:40 UTC, nugaon commented on test/modules/debug/settlements.spec.ts
> +      // FIXME this is due to a bug in Bee
you commented 12 hours ago it is fixed in Bee PR [#1213](https://github.com/ethersphere/bee/pull/1213).
could you correct this?

2021-02-09 09:31 UTC, merged