feat: feeds endpoint
ethersphere/bee-js pull request #125
Opened 2021-02-08 20:30 UTC by agazso

2021-02-12 15:41 UTC, nugaon requested changes

2021-02-12 15:41 UTC, nugaon commented on src/chunk/upload.ts
> +}
same function defined in `src/chunk/soc.ts` (and should remain there)

2021-02-12 15:41 UTC, nugaon commented on src/modules/feed.ts
> +  topic: string,
we should provide a specific type for that with a helper function which provide this type from the given string and actually checks the given topic string satisfies the requirements for a hex topic.
this helper function should be exposed through `Utils`.

2021-02-12 15:41 UTC, nugaon commented on src/modules/feed.ts
> +export interface FindFeedUpdateResponse extends ReferenceResponse, FeedUpdateHeaders {}
would be nice if the interfaces in a file preceed the functions

2021-02-12 15:41 UTC, nugaon commented on src/modules/feed.ts
> + * @param options     Additional options, like index, at, type
default `type` of feed is not defined

2021-02-12 15:42 UTC, vojtechsimetka commented on src/utils/bytes.ts
> +}
Could you document these functions as well? Since the `utils.bytes` is now exported to the users.

2021-02-12 15:42 UTC, vojtechsimetka commented on src/modules/feed.ts
> + * Find feed update
```suggestion
 * Retrieve specified feed update
 * if no options are provided, retrieve the latest feed update
```

2021-02-12 15:42 UTC, vojtechsimetka commented on src/modules/feed.ts
> +export async function findFeedUpdate(
Probably better naming would be `retrieveFeedUpdate`

2021-02-12 15:44 UTC, nugaon commented on src/modules/feed.ts
> +export async function findFeedUpdate(
or maybe `fetchFeed`?

2021-02-12 15:46 UTC, vojtechsimetka commented
About the tests, maybe we can just post a hardcoded value in the tests for the feeds? So really just string or array of bytes representing the feed updates and then retrieving it.

2021-02-15 10:32 UTC, agazso commented on src/modules/feed.ts
> +  topic: string,
This is a good idea, however I think it's outside the scope of this PR. Created an issue for it: https://github.com/ethersphere/bee-js/issues/137

2021-02-15 10:35 UTC, agazso commented on src/modules/feed.ts
> + * @param options     Additional options, like index, at, type
I usually follow the API conventions, so for example in this case when the `type` is an optional query parameter then it is also an optional parameter of the endpoint wrapper function. The default in this case is defined on the API endpoint itself.

https://docs.ethswarm.org/api/#tag/Feed/paths/~1feeds~1{owner}~1{topic}/get

2021-02-15 10:51 UTC, agazso commented on src/modules/feed.ts
> + * Find feed update
I usually follow the naming of the Bee documentation so that it's clear which endpoint the function refers to. However in this case I agree that this is not the best name. The issue may be that the endpoint actually does several things:
- find a feed update with the given parameters
- return the data of the feed update
- also return the index and the subsequent index of the the feed update in headers

https://docs.ethswarm.org/api/#tag/Feed/paths/~1feeds~1{owner}~1{topic}/get

2021-02-15 10:57 UTC, agazso commented on src/modules/feed.ts
> +export async function findFeedUpdate(
See my other comment explaining the weirdness around this name. With other endpoints (and the Bee interface as well) we are using `download...` and `upload...` so for the sake of consistency I think a better name would be `downloadFeedUpdate`.

WDYT?

2021-02-15 13:15 UTC, vojtechsimetka approved these changes

2021-02-15 13:15 UTC, vojtechsimetka commented on src/modules/feed.ts
> + * Find feed update
Right, then lets just be more explicit about it. `Find feed update` is extremely cryptic.

2021-02-15 13:15 UTC, vojtechsimetka commented on src/modules/feed.ts
> +export async function findFeedUpdate(
`downdloadFeedUpdate` in me indicates downloading the actual file behind the feed. I like `fetchFeed`.

2021-02-15 15:51 UTC, agazso commented on src/modules/feed.ts
> + * Find feed update
I added a comment explaining what it does.

2021-02-15 15:52 UTC, agazso commented on src/modules/feed.ts
> +export async function findFeedUpdate(
I ended up renaming it to `fetchFeedUpdate` along with a comment explaining why.

2021-02-16 09:21 UTC, nugaon approved these changes
LGTM!
feed topic helper function can be provided in the next subsequent PR

2021-02-16 09:22 UTC, merged