refactor: verify to assert
ethersphere/bee-js pull request #255
Opened 2021-04-09 15:51 UTC by AuHau

Closes #211 

This is work I had in progress already since last week, so I have wrapped it up as it was getting rather stale.

2021-04-09 15:57 UTC, vojtechsimetka approved these changes
LGTM

2021-04-12 07:45 UTC, nugaon requested changes
I also like it in this new structure, but there were some JSDoc issues, can you fix those?

2021-04-12 07:45 UTC, nugaon commented on src/utils/bytes.ts
> +  b: unknown,
Here you don't follow your convention (as you can see below at `assertFlexBytes`)

2021-04-12 07:45 UTC, nugaon commented on src/utils/bytes.ts
> +export function assertFlexBytes<Min extends number, Max extends number = Min>(
jsdoc parameter order is wrong

2021-04-12 07:45 UTC, nugaon commented on src/utils/bytes.ts
> +export function bytesAtOffset<Length extends number>(data: Uint8Array, offset: number, length: Length): Bytes<Length> {
jsdoc parameter order is wrong

2021-04-12 07:45 UTC, nugaon commented on src/utils/bytes.ts
> +export function isBytes<Length extends number>(b: unknown, length: Length): b is Bytes<Length> {
jsdoc parameter order is wrong

2021-04-12 07:45 UTC, nugaon commented on src/utils/bytes.ts
> +export function assertBytes<Length extends number>(b: unknown, length: Length): asserts b is Bytes<Length> {
jsdoc parameter order is wrong

2021-04-12 08:05 UTC, AuHau commented
Thanks @nugaon will fix those! I thought that if the name of variable is mentioned the order does not matter, but I guess it matters.

2021-04-12 09:32 UTC, nugaon approved these changes

2021-04-12 10:41 UTC, agazso approved these changes
Looks good!

2021-04-12 11:14 UTC, merged