refactor: basic conventions
ethersphere/bee-js pull request #3
Opened 2020-11-11 22:25 UTC by nugaon

## Features

- added eslint rules, prettier and tsconfig to the project,
- refactor the already existing code by that,
- created `npm run format` command for rewrite all ts files in src/** and test/**
- defined VSCode settings for auto-correcting on save and use Prettier 

## TODO
- [x] Redesign GitHub Workflow (browser tests)
- [x] Change README
- [x] Webpack integration
- [x] Replace Karma with Jest
- [x] Remove Tasegir dependency
- [x] Browser tests

2020-11-23 08:59 UTC, agazso commented
I think it would be better to merge this to the `main` branch now

2020-12-03 07:14 UTC, vojtechsimetka commented on package.json
>      "compile:watch": "tasegir compile -- --watch",
remove

2020-12-03 07:24 UTC, vojtechsimetka requested changes

2020-12-03 07:24 UTC, vojtechsimetka commented on package.json
>      "release": "tasegir release",
remove

2020-12-03 07:24 UTC, vojtechsimetka commented on package.json
>      "postinstall": "patch-package",
remove

2020-12-03 07:24 UTC, vojtechsimetka commented on src/utils/data.ts
> +  return readableData
This means, that from now on the nodejs implementation also does not utilise data streaming, and instead puts everything in buffer, right?

2020-12-03 07:24 UTC, vojtechsimetka commented on .mocharc.yaml
> +# This is an example Mocha config containing every Mocha option plus others
Do we need mocha config when we are using Jest?

2020-12-03 07:24 UTC, vojtechsimetka commented on karma.conf.ts
> +
Do we need karma config when we are using Jest?

2020-12-03 07:24 UTC, vojtechsimetka commented on package.json
> +    "test": "jest --config=jest.config.ts",
Could we separate browser and nodejs tests?

2020-12-03 12:57 UTC, agazso commented on package.json
> +    "test": "jest --config=jest.config.ts",
I propose let's merge this and open issues for the topics that @vojtechsimetka raised.

2020-12-03 12:57 UTC, agazso commented
I propose let's merge this and open issues for the topics that @vojtechsimetka raised.

2020-12-03 12:58 UTC, agazso approved these changes
I propose let's merge this and open issues for the topics that @vojtechsimetka raised.

2020-12-03 12:58 UTC, vojtechsimetka commented
I agree

2020-12-03 12:58 UTC, vojtechsimetka approved these changes

2020-12-03 13:16 UTC, nugaon commented on package.json
>      "postinstall": "patch-package",
The building process could read the libraries/files that differ on NodeJS<->Browser side from this list. Although it is not implemented yet.

2020-12-03 13:17 UTC, nugaon commented on package.json
> +    "test": "jest --config=jest.config.ts",
Yes, we can

2020-12-03 13:18 UTC, nugaon commented on karma.conf.ts
> +
No, we don't need I will delete it in the next commit

2020-12-03 13:18 UTC, nugaon commented on .mocharc.yaml
> +# This is an example Mocha config containing every Mocha option plus others
No, we don't need I will delete it in the next commit

2020-12-03 13:28 UTC, nugaon commented on package.json
> +    "test": "jest --config=jest.config.ts",
Yes, it is possible, I put that into the NPM scripts in the next change

2020-12-03 15:37 UTC, merged