feat: new debug postage api
ethersphere/bee-js pull request #381
Opened 2021-07-29 15:55 UTC by AuHau

2021-07-30 08:35 UTC, AuHau commented
It bit depends if the Bee's rename PR will be merged or not https://github.com/ethersphere/bee/pull/2371

2021-07-30 14:49 UTC, nugaon requested changes
I commented two type issues, but others seems good.

On local test run I got error:

```
  ● Bee Debug class › PostageBatch › should have both immutable true and false

    Internal Server Error: cannot create batch
```

2021-07-30 14:49 UTC, nugaon commented on src/bee-debug.ts
> +  async getPostageBatch(postageBatchId: BatchId | string): Promise<PostageBatch> {
```suggestion
  async getPostageBatch(postageBatchId: BatchId | string): Promise<DebugPostageBatch> {
```

2021-07-30 14:49 UTC, nugaon commented on src/bee-debug.ts
> +  async getAllPostageBatch(): Promise<PostageBatch[]> {
```suggestion
  async getAllPostageBatch(): Promise<DebugPostageBatch[]> {
```

2021-07-30 14:52 UTC, nugaon commented on src/bee-debug.ts
> +  async getPostageBatch(postageBatchId: BatchId | string): Promise<PostageBatch> {
Don't commit these changes because the source file does not have `DebugPostageBatch` import.

2021-08-02 12:58 UTC, nugaon approved these changes
LGTM!

2021-08-02 12:58 UTC, merged