feat: bytes module
ethersphere/bee-js pull request #50
Opened 2020-12-16 13:24 UTC by agazso

Add `/bytes` endpoint wrappers.

2020-12-16 17:45 UTC, nugaon requested changes

2020-12-16 17:45 UTC, nugaon commented on src/modules/pinning.ts
> +}
(un)pinCollection, (un)pinFile and (un)pinData are literally the same. it should be one function with some enum parameter, which decides what endpoint should be called.

2020-12-16 17:45 UTC, nugaon commented on test/index.spec.ts
> +      const hash = await bee.uploadFile(content)
most of the tests upload this same content. Maybe It could be better to place it in `beforeAll` hook func.

2020-12-16 17:45 UTC, nugaon commented on test/modules/bytes.spec.ts
> +    const invalidReference = '0000000000000000000000000000000000000000000000000000000000000000'
this would be better in `utils.ts` file as an exported constant as we use it regurarly.

2020-12-16 17:45 UTC, nugaon commented on test/modules/bytes.spec.ts
> +    const invalidReference = '0000000000000000000000000000000000000000000000000000000000000000'
this would be better in `utils.ts` file as an exported constant as we use it regurarly.

2020-12-16 17:45 UTC, nugaon commented on test/modules/pinning.spec.ts
> +      const response = await pinning.pinData(BEE_URL, hash)
same as I mentioned at the other test file. From the perspective of the test, it's not necessary to upload at any cases

2020-12-16 18:00 UTC, agazso commented on src/modules/pinning.ts
> +}
Good idea

2020-12-16 18:00 UTC, agazso commented on test/index.spec.ts
> +      const hash = await bee.uploadFile(content)
They upload the same content but because they use different functions the resulting hash will be different. Files are basically bytes + metadata, and manifests add even more metadata to store the paths.

2020-12-16 18:02 UTC, agazso commented on test/modules/pinning.spec.ts
> +      const response = await pinning.pinData(BEE_URL, hash)
See my other comment regarding this

2020-12-17 13:55 UTC, nugaon requested changes

2020-12-17 13:55 UTC, nugaon commented on src/modules/pinning.ts
> +}
The whole file is more clear now, although I would change the `endpoint` to an enum typed or literal typed parameter, like `pinnableStructure: 'collection' | 'file' | 'bytes'` and let these functions construct the URLs based on that parameter. Thereby, you don't need those wrapping functions and the code is more transparent and maintainable.

2020-12-17 14:58 UTC, agazso commented on src/modules/pinning.ts
> +}
Changed the endpoint parameter on pin and unpin to enums.

2020-12-17 15:45 UTC, nugaon approved these changes

2020-12-18 15:18 UTC, merged