test: real browser
ethersphere/bee-js pull request #51
Opened 2020-12-17 08:31 UTC by nugaon

I made a new compile command `npm run compile:window` which makes a bundle for testing in real browsers.

The code that it generates is the same as the already existing ones, except it assignes a initialized Bee class to the global object 
`window` in browsers. Thereby It is possible to run test in Jest within browser context, or do manual tests in the real browser itself by opening [test/testpage/testpage.html](test/testpage/testpage.html). 

I've created examples how to write Jest test with Puppeteer.

it resolves issue #42 
It closes PR #47

2020-12-17 15:23 UTC, agazso requested changes

2020-12-17 15:23 UTC, agazso commented on test/testpage/testpage.ts
> +window.beeFactory = (...params: ConstructorParameters<typeof Bee>) => new Bee(...params)
Maybe I miscommuncited but the idea was to make Bee available in the browser context (for example by having `window.Bee = Bee`) and then in make an instance in the tests, like how it is used in `index.spec.ts`. Then you don't need to inject __BEE_URL__ but you can just simply use the `beeUrl` function from `utils` similarly to the other tests.

2020-12-17 15:42 UTC, nugaon commented on test/testpage/testpage.ts
> +window.beeFactory = (...params: ConstructorParameters<typeof Bee>) => new Bee(...params)
beeFactory provides you Bee instance with any arbitrary config, which basically the same thing that you would do with the direct binding. It's not necessary to make an instance in tests, because you can use the default `window.bee` object for most of the cases.
Unfortunately the `beeUrl` function in utils cannot be called from browser context, because it calls `process`, which is a NodeJS global.

2020-12-17 15:54 UTC, nugaon commented on test/testpage/testpage.ts
> +window.beeFactory = (...params: ConstructorParameters<typeof Bee>) => new Bee(...params)
But I see your point, anyway it works well now and you even don't have to initiailze that at every tests.

2020-12-18 15:20 UTC, agazso approved these changes

2020-12-18 15:20 UTC, agazso commented on test/testpage/testpage.ts
> +window.beeFactory = (...params: ConstructorParameters<typeof Bee>) => new Bee(...params)
Ok, let's keep it this way for now

2020-12-20 10:36 UTC, merged