feat: bmt hasher
ethersphere/bee-js pull request #65
Opened 2021-01-06 15:40 UTC by agazso

2021-01-10 13:27 UTC, nugaon requested changes

2021-01-10 13:27 UTC, nugaon commented on src/chunk/bmt.ts
> +  while (input.length > HASH_SIZE) {
instead of `>` I would use `!==`, because it expresses better the goal of the iteration. Anyway it also works fine.

2021-01-10 13:27 UTC, nugaon commented on test/chunk/bmt.spec.ts
> +    const payload = new Uint8Array([1, 2, 3])
This test input could be debatable in that sense it even doesn't fill one segment.
Of course, basically we hash this with zeros that still represent data in the operation, but the function could operate well in the first cycle and then regardless of the input data could hash the same things.

2021-01-11 11:13 UTC, agazso commented on src/chunk/span.ts
> +  if (length > 2 ** 32 - 1) {
Added a constant `MAX_SPAN_LENGTH` along with the comment

2021-01-11 11:14 UTC, agazso commented on src/chunk/bmt.ts
> +const SEGMENT_SIZE = 32
Added a constant `SEGMENT_PAIR_SIZE` that is the double of `SEGMENT_SIZE` and changed the comment to explain better what's going on.

2021-01-11 11:14 UTC, agazso commented on src/chunk/bmt.ts
> +  while (input.length > HASH_SIZE) {
Fixed

2021-01-11 11:18 UTC, agazso commented on test/chunk/bmt.spec.ts
> +    const payload = new Uint8Array([1, 2, 3])
There are three tests:
1. This is the first test and indeed it doesn't fill one segment. However we use this test data in multiple tests including the chunk upload test with the same hardcoded hash to make sure it produces the same result. If the filling with zeroes would not work correctly it would produce a different hash.
2. The second one tests with different sizes from 1 to 4096 doubling in each iteration.
3. The third test fills a complete 4096 bytes length chunk with random data

2021-01-11 17:58 UTC, nugaon commented on test/chunk/bmt.spec.ts
> +    const payload = new Uint8Array([1, 2, 3])
with this 3rd test is fine, thanks!

2021-01-11 17:59 UTC, nugaon approved these changes

2021-01-12 07:37 UTC, merged