chore!: drop node 12 support
ethersphere/bee-js pull request #741
Opened 2022-07-27 14:12 UTC by AuHau

Closes #699

2022-07-27 14:17 UTC, vojtechsimetka requested changes
Can you also update the versions in README?

The node version should be `14.0.0` and npm version should be `6.14.4`

2022-07-27 14:18 UTC, vojtechsimetka commented on README.md
>  ![](https://img.shields.io/badge/npm-%3E%3D6.9.0-orange.svg?style=flat-square)
```suggestion
![](https://img.shields.io/badge/npm-%3E%3D6.14.4-orange.svg?style=flat-square)
```

2022-07-27 14:21 UTC, vojtechsimetka approved these changes

2022-07-27 14:32 UTC, merged

2022-07-28 13:45 UTC, bee-worker commented
Release [v5.0.0](https://github.com/ethersphere/bee-js/releases/tag/v5.0.0) addresses this.